### ISSUE TITLE
Using pushNewScreen don't open navigation bar 

### ISSUE THREAD

**Issue by Sang-Nguyen-25** [jb3rndt/PersistentBottomNavBarV2#12]
I am using the latest version: 4.1.8, 
But using pushNewScreen I can't see the navigation bar when withNavBar set true.
```
            pushNewScreen(
              context,
              screen: CartPage(),
              withNavBar: true,
              pageTransitionAnimation: PageTransitionAnimation.cupertino,
            );
```
Tab 1 -> Sub page -> using pushNewScreen -> Tab 3
Tab 2 
Tab 3
Tab 4
Can you help me from sub page from Tab 1 navigable to tab 3 where navigation bar shows up?

**Comment by jb3rndt** [comment]
If I understand correctly, you need to use your `PersistentTabController` and use the `jumpToTab` method to go to Tab 3. I cand find out why you cant see the navbar after pushing with `withNavBar: true`. Take a look at this full example which hopefully does what you wanted. Maybe it helps you solve your issue. Otherwise give me feedback on what I got wrong or what still doesnt work :)

<details>
  <summary>Full code example</summary>
  
import 'package:flutter/material.dart';
import 'package:persistent_bottom_nav_bar_v2/persistent-tab-view.dart';

void main() => runApp(PersistenBottomNavBarDemo());

class PersistenBottomNavBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Persistent Bottom Navigation Bar Demo',
      home: TabView(),
    );
  }
}

class TabView extends StatefulWidget {
  TabView({Key key}) : super(key: key);

  @override
  _TabViewState createState() => _TabViewState();
}

class _TabViewState extends State<TabView> {
  PersistentTabController _controller;

  @override
  void initState() {
    super.initState();
    _controller = PersistentTabController(initialIndex: 0);
  }

  List<Widget> _buildScreens() {
    return [
      Tab1(controller: _controller),
      Tab2(controller: _controller),
      Tab3(controller: _controller),
      Tab4(controller: _controller),
    ];
  }

  List<PersistentBottomNavBarItem> _navBarsItems() {
    return [
      PersistentBottomNavBarItem(
        icon: Icon(Icons.home),
        title: "Tab1",
      ),
      PersistentBottomNavBarItem(
        icon: Icon(Icons.search),
        title: "Tab2",
      ),
      PersistentBottomNavBarItem(
        icon: Icon(Icons.add),
        title: "Tab3",
      ),
      PersistentBottomNavBarItem(
        icon: Icon(Icons.message),
        title: "Tab4",
      )
    ];
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Navigation Bar Demo')),
      body: PersistentTabView(
        context,
        controller: _controller,
        screens: _buildScreens(),
        items: _navBarsItems(),
        navBarStyle: NavBarStyle.style1,
      ),
    );
  }
}

class Tab1 extends StatelessWidget {
  final PersistentTabController controller;
  Tab1({this.controller});
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text("Tab 1"),
            ElevatedButton(
              onPressed: () {
                pushNewScreen(context,
                    screen: SubPage(controller: controller), withNavBar: true);
              },
              child: Text("Go to subpage"),
            ),
          ],
        ),
      ),
    );
  }
}

class SubPage extends StatelessWidget {
  final PersistentTabController controller;
  SubPage({this.controller});
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text("Sub Page"),
            ElevatedButton(
              onPressed: () {
                this.controller.jumpToTab(2);
              },
              child: Text("Go to Tab 3"),
            ),
          ],
        ),
      ),
    );
  }
}

class Tab2 extends StatelessWidget {
  final PersistentTabController controller;
  Tab2({this.controller});
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text("Tab 2"),
      ),
    );
  }
}

class Tab3 extends StatelessWidget {
  final PersistentTabController controller;
  Tab3({this.controller});
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text("Tab 3"),
      ),
    );
  }
}

class Tab4 extends StatelessWidget {
  final PersistentTabController controller;
  Tab4({this.controller});
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Text("Tab 4"),
      ),
    );
  }
}

</details>
