### ISSUE TITLE
Error when adding navigator observer 

### ISSUE THREAD

**Issue by mgaucher** [jb3rndt/PersistentBottomNavBarV2#30]
Hello,

 I added a navigator observer in my PersistentTabView.custom widget like this 
```
 routeAndNavigatorSettings: CustomWidgetRouteAndNavigatorSettings(
            navigatorObservers: [StackNavigatorObserver()],
            onGenerateRoute: AppRouter.onGenerateRoute,
          ),
```
But when I switch tab I have this error :

'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3232 pos 14: 'observer.navigator == null': is not true.

I don't know if it's a bug or if I miss something

**Comment by jb3rndt** [comment]
I think you indeed found a bug there. If I'm correct, the problem is that the specified observers get shared across all tabs. So when switching to another tab, the underlying Navigator (of which one separate is created for each tab) wants to set himself to be observed. That is where the assertion fails.
I dont know what the correct way of solving would be, but one way would be to have a List of Lists of NavigatorObservers, so that one has to specify the observers for each tab separately.

In the end it would be used like this:
```dart
 routeAndNavigatorSettings: CustomWidgetRouteAndNavigatorSettings(
  navigatorObservers: [[StackNavigatorObserver()], [], [], [], []],
  onGenerateRoute: AppRouter.onGenerateRoute,
),
```

The length has to match the number of tabs then. In this case, only the first Tab would be observed as the Lists for the other tabs are empty. In general I think it is not possible to share one Observer across multiple Navigators.

Do you think that would be a valid solution?

**Comment by mgaucher** [comment]
Yes this is what I need ! Do you think you can update the package to make it works ?

**Comment by mgaucher** [comment]
By the way, with Flutter 3.0 they are warnings, SchedulerBinder don't need null check anymore
 
    WidgetsBinding.instance!.addPostFrameCallback((_) {
                   ^
: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
../…/lib/persistent-tab-view.widget.dart

**Comment by jb3rndt** [comment]
It should now work in the new version [4.2.0](https://github.com/jb3rndt/PersistentBottomNavBarV2/tree/v4.2.0) :)
I hope it works in your use case

**Comment by mgaucher** [comment]
This is working, thanks a lot
