### ISSUE TITLE
A borderRadius can only be given for a uniform Border. 

### ISSUE THREAD

**Issue by alexaung** [jb3rndt/PersistentBottomNavBarV2#31]
I got this error when I change to persistent_bottom_nav_bar_v2 from persistent_bottom_nav_bar.

**Comment by jb3rndt** [comment]
I'm not sure where this error happens. Can you provide the stack trace or give a scenario where this happens?
Maybe these links will be helpful if you've not yet come across those: [StackOverflow](https://stackoverflow.com/questions/58812778/a-borderradius-can-only-be-given-for-uniform-borders), [GitHub Gists](https://gist.github.com/rohan20/d12a709a27511304c853334dd636ba63)

**Comment by alexaung** [comment]
@jb3rndt Thanks for reply.

This is GitHub link. [https://github.com/alexaung/persistent_bottom_nav_bar_v2](url)

If you roll back to persistent_bottom_nav_bar, it is working.

**Comment by jb3rndt** [comment]
Ok thank you both, I found the issue. This error is thrown when using BorderRadius.zero, although there will be no radius. The borderRadius has to be null instead, so this failed because BorderRadius.zero was set as default.
It should be resolved with version [4.2.2](https://github.com/jb3rndt/PersistentBottomNavBarV2/releases/tag/v4.2.2) 👍
