### ISSUE TITLE
Best practice for Fade Transition

### ISSUE THREAD

**Issue by NightSkyDev** [jb3rndt/PersistentBottomNavBarV2#38]
Hello and thank you for continuing this library!  

This is my first time using this library and I need a fade transition when changing between main screens.  (The default appears to be a slide transition?)  Reading through the comments/posts from this and the previous version, it seems like the only way to change the transition is to use pushNewScreen() and specifying the transition?  Is there a better way?

When I use pushNewScreen(),  the nav bar is disappearing.  I'm using the "example" code and adding the following code to the onPressed event in the PersistentBottomNavBarItem declaration:

`onPressed: (_) {
	pushNewScreen(context,
	    screen: HomeScreen(),
	    withNavBar: true,
	    pageTransitionAnimation: PageTransitionAnimation.fade);
 },`

Thanks for your help!
 
btw - I tried using the context passed on on the onPressed event, but I get a null error on the context at runtime.

**Comment by NightSkyDev** [comment]
Update: I fixed the disappearing nav bar by saving the context from selectedTabScreenContext and passing that context.  Feels like a hack, so I go back to the original question if this is the best way?

I have another questions about the icon colors (I need to change the icon background color).  Is it better for me to open a new issue for that?

**Comment by jb3rndt** [comment]
Wow I didnt know it is possible to change the transition this way (https://github.com/jb3rndt/PersistentBottomNavBarV2/issues/17). It is hacky indeed because it is not supported by the package to use different transitions. So there is no best practice either.
The solution might work for you though, if you do not rely on `stateManagement` because that will get lost with that.
What the `onPressed` causes in the background is that it overrides the whole automatic tab switching mechanism and just executes your function instead. So I cannot guarantee that it works in all cases.

Yes please open a new issue for the icon thing and add an example if possible

**Comment by NightSkyDev** [comment]
>The solution might work for you though, if you do not rely on stateManagement because that will get lost with that.
Yes, the state management being lost is going to be an issue for me.  Thank you for pointing it out!

**Comment by jb3rndt** [comment]
Ok then, I'LL try to think of a way to solve it. Or do you already have an idea?
