### ISSUE TITLE
How to use another persistent widget like a mini player on top of the Persistent Nav Bar 

### ISSUE THREAD

**Issue by mrripp3r** [jb3rndt/PersistentBottomNavBarV2#40]
Hi, I was using a "DIY" navigation bar that allowed me to use a mini player and show it across screens through the use of a stack inside the main body. Regardless of the tab bar view, I was able to see my mini player. Since moving to this new package because of some unique features, I haven't been able to implement my mini player using the same technique. How can I go about this? I would like to have my mini player appear everywhere the bottom nav bar does. 

See image below

![Persistent mini player](https://user-images.githubusercontent.com/63537009/174822141-06679923-edfb-4ae4-be23-488056146fab.png)

**Comment by mrripp3r** [comment]
Gonna try this approach and let you know. My custom method had fewer
functionalities compared to what this package seems to offer. It's why I'm
switching

**Comment by mrripp3r** [comment]
> jb3rndt

This is exactly what I want to do using this package. The implementation is still failing

**Comment by jb3rndt** [comment]
Why does it fail?

**Comment by mrripp3r** [comment]
> Why does it fail?

It fails because in this package the body which acts as a viewport seems to be pre-created under List<Widget>[]... I would be able to do what I want if this was a body instead as part of a scaffold where I would use a Stack to have my mini player below. I hope this makes sense

**Comment by jb3rndt** [comment]
Ok I understand what you mean now. It would require some rework in the package because as of now, every screen spans the whole height of the phone screen - even behind the navbar (as long as you are not using `PersistentBottomTabView.custom`). So what would happen right now is that the miniplayer is behind the navbar. Do you know if the miniplayer allows to set some kind of bottom offset, so one could say that it should be shifted up by 60px?

**Comment by jb3rndt** [comment]
This should be possible with version 5.x.x of the package. Please open a new issue if you run into problems with that :)
