### ISSUE TITLE
Navigator 2.0 (Beamer, go_router, ...)

### ISSUE THREAD

**Issue by DynxstyGIT** [jb3rndt/PersistentBottomNavBarV2#83]
Hey, are there any plans for Navigator 2.0 support? (Deep links, URL based on selected tab, ...) Or is there already a workaround for that?

**Comment by jb3rndt** [comment]
Not yet, what would you need for a Navigator 2.0 Support? Just the `pages` and `onPopPage` parameters?

**Comment by DynxstyGIT** [comment]
Well the url would have to change depending on the currently selected tab - while also keeping the navbar

**Comment by jb3rndt** [comment]
You could change the url by using the `onIndexChanged` callback of the `PersistentTabController` like so:
```
controller.onIndexChanged = (value) {
  GoRouter.of(context).go("/$value");
};
```

Apart from that, I dont really know what exactly the package could provide to make Navigator 2.0 compatible. So feel free to post a minimal example or open a PR.

**Comment by jb3rndt** [comment]
Yeah that seems to be a bit trickier. It seems that go_router hat the `ShellRoute` for that. As the router builds its own navigation stack automatically and just passes the finished `child` to the `ShellRoute`, its hard to integrate. What I tested was allowing the `PersistentTabView` to take a `child` (like it is intended by `ShellRoute`), which would be used instead of everything internally that makes the tab-switching possible. But as a consequence all the features and logic of the `PersistentTabView` would get lost, thus making the usage of the nav bar packege obsolete.
So you have another idea?

**Comment by DynxstyGIT** [comment]
Hmm, not sure. Been struggling with Beamer for at least 3 weeks now, as I just cannot find any good examples on how to dynamically push pages with and without a navbar.

**Comment by jb3rndt** [comment]
I created a first version of a go_router integration. Look here for more: https://github.com/jb3rndt/PersistentBottomNavBarV2/issues/24#issuecomment-1722439987. Closing as a duplicate.
