### ISSUE TITLE
Ability to reset a tab's state programmatically, when state management is on

### ISSUE THREAD

**Issue by kbessemer** [jb3rndt/PersistentBottomNavBarV2#95]
**Is your feature request related to a problem? Please describe.**
The problem is that at times I want my tab's state to be preserved, but at times I want it reset.

**Describe the solution you'd like**
I would like to programmatically be able to reset a tab's state. I'd like to be able to do this while inside the current tab, no matter how many levels deep. And also when I am not in the targeted tab.

**Comment by jb3rndt** [comment]
Do you want to remove all the routes of that current tab to return to the original tab page, or do you want to discard the whole state of the original tab view (including any data that was loaded, scroll position and so on)

**Comment by Gray-Codev-29** [comment]
is this possible?

**Comment by jb3rndt** [comment]
You can always pop the screens of the tab you want with this snippet:
```
Navigator.popUntil(
  context,
  ModalRoute.withName(
      Navigator.defaultRouteName,
  ),
);
```

If you need the context of a specific tab, you can pass `RouteAndNavigatorSettings` with a navigator key to each of your `PersistentBottomNavBarItem`. Then you can get the context of the respective navigator key.

What exactly do you want to achieve?

**Comment by Gray-Codev-29** [comment]
for me, i want to do something similar to this,

first screen < this loads every thing in initial state, variables etc, like for example selectedIndex = 0, along the way, this can change inside this screen such as selectedindex= 2 , if i do setstate,

then on going to second screen, it will do same thing initialize all default values of my variable on what i have indicated,

now what i want is when i go from second to first, i want to have all the selectedindex from firstscreen be back to its default initialzie value, doing navigator.pop wont do this, i tried popuntil as well, and statemanagement : false, 

hope you can help me out, if this wont work, what i can do is either set those values in a statemanagement or shared preferences then change them back when going back to that screen or use freeze instead. but this  i hope is my last resort. 

please help

**Comment by jb3rndt** [comment]
Hi, from what I understand, I would not say that this package is responsible for that. Here are a few suggestions to accomplish what you need anyway:
Option 1: push your second screen with `Navigator.pushReplacement` -> go back to your first screen by also using `Navigator.pushReplacement`. This effectively destroys the first screen because it is not kept in the navigator stack

Option 2: you can await the `Navigator.push` in your first screen, so after you popped the second screen, you can re-run your initialization logic (just put that logic into a separate function)

I hope that helps a bit. If not, please post a code example so I can try it out.
